apiVersion: v1
kind: Secret
metadata:
  name: fn-secrets
  namespace: foreseesnetwork
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  EMAIL_USER: "foreseesnetwork@gmail.com"
  EMAIL_PASS: "aoivchjwxrbwmjxv"